### ISSUE TITLE
Script de Comunicação Socket e Arduino Uno

### ISSUE THREAD

**Issue by Joanna-Victoria** [Gleicianegaldino/ThingSafe#2]
**Nós, como** desenvolvedores, **queremos** utilizar a comunicação entre Socket e Arduino **para** fazer a alimentação de dados na interface.

- [x] Script

**Comment by davisouzaluna** [comment]
# Simulador comunicação IOT

Para ser feita a simulação do dispositivo IOT, primeiro execute o instalador de pendências:

https://github.com/Gleicianegaldino/ThingSafe/blob/99c2ce6a4ec545b5c8b4bb0788c3277ff99b1fbf/instalador-pendencias.sh#L1-L42

Para executar digite 
 ```cl
bash instalador-pendencias.sh
```

## **Códigos:**
No arquivo publisher.py você pode alterar o tópico e o broker à sua escolha. Mas lembre de colocar o mesmo tópico e broker no Subscriber.py

**Código do publisher(simulador):**
https://github.com/Gleicianegaldino/ThingSafe/blob/99c2ce6a4ec545b5c8b4bb0788c3277ff99b1fbf/publisher.py#L1-L27

**Código do Subscriber:**

https://github.com/Gleicianegaldino/ThingSafe/blob/088a37884aa213ee129df859ba0fc060588eb3f8/subscriber.py#L1-L92


## Iniciando a simulação
Depois de instalar as pendências, inicie o publisher(simulador em paho-mqtt).
```cl
python3 publisher.py
```

Abra outra janela do terminal, execute o subscriber.

```cl
python3 subscriber.py
```

Agora, verifique a pasta em que o subscriber se encontra. Um arquivo json foi criado, com os respectivos dados

**Comment by davisouzaluna** [comment]
No meu caso, quando uso a WSL, às vezes pode acontecer um erro na execução do mosquitto(no momento de inicializar o serviço do mesmo). Um dos erros comuns é: `unable to write pid file`.
Para resolvê-lo, é só criar uma pasta mosquitto e atribuir o nome desse ficheiro para o usuário mosquitto. Faça isso com o comando:

```cl
sudo mkdir /var/run/mosquitto/ && sudo chown mosquitto: /var/run/mosquitto
```
Logo após, dentro do arquivo mosquitto.conf em modo de superusuário, adicionamos uma linha:
`pid_file /var/run/mosquitto/mosquitto.pid`. Caso essa linha já exista, só altere a mesma. Os comandos para chegar a tal configuração são:
```cl
sudo nano /etc/mosquitto/mosquitto.conf
```

Depois, verifique se o serviço está rodando: 

```cl
sudo service mosquitto status
```

Caso não esteja rodando(com a mensagem `mosquitto is not running`), inicie com:
```cl
sudo service mosquitto start
```

**Comment by davisouzaluna** [comment]
Hoje, 07/04/2023, achei uma solução para o problema da criação do arquivo JSON, que antes era incompatível(ou não começava com os colchetes ou tinha diversos colchetes). A solução é a substituição do json a cada iteração com a fila de mensagem do broker a partir do método json.append().


### Código do subscriber contendo uma linha de um json que se atualiza a cada segundo(Caso você copie o código, não se esqueça da identação)
```cl
import paho.mqtt.client as mqtt 
import time 
import json
import sys
  
#some comments are writted in portuguese. If you want to know about, you can use the google tradutor :p 
 
HOST= "test.mosquitto.org"#If you want to set this parameter in a public host, is very important to you remember to choose a topic(only you use) 
PORT=1883#This is a mosquitto port(when i start my broker) 
keepalive=60 
bind_address="" 
TOPIC=[("microondas",0),("ultrassom",0)]#tupla com tópico e QoS. Pode-se adicionar diversos tópicos e alterar o QoS caso queira 
 
#Só para relembrar: QoS=0 significa que a entrega da mensagem será feita com o melhor esforço, sendo assim adicionada à fila do broker e não tendo a confirmação que o subscriber irá receber a mensagem. Resumindo, a mensagem não é armazenada 
#QoS=1 significa que há uma garantia de que pelo menos uma vez a mensagem irá ser entregue ao receptor 
#QoS=2 significa que a mensagem irá ser recebida apenas uma vez pelo receptor(é mais lento, mas mais confiável) 
 
  
def on_connect(client, userdata, flags, rc): 
     
    if rc == 0: 
        print("Connected with result code "+str(rc)) 
        global Connected#Torna a variável Connected global 
        Connected = True#"ativa" a variável 
              
    else: 
        print("Falha na conexão") 
  
  
Connected = False #Variável global utilizada como referência para saber se o subscriber está conectado ao broker. 


def on_message(client, userdata, msg):
    print("=============================") 
    print("Topic: "+str(msg.topic) )
    print("Payload: "+str(msg.payload)) 
    print("=============================") 
    
    for i in range(len(TOPIC)):
        if((msg.topic,msg.qos)==TOPIC[i]):
            mensagem={  
                'mensagem': int(msg.payload),
                'topico': str(msg.topic),
                'qos': str(msg.qos)#Caso queira salvar como um inteiro você digita: 
                };
            
            with open(f'{msg.topic}.json','w') as f:
                pass
            with open(f'{msg.topic}.json','r') as f:
                conteudo_json=f.read()
                if not conteudo_json:
                    with open(f'{msg.topic}.json','w') as s:
                        json.dump([],s)
            with open(f'{msg.topic}.json','r') as f:
                guardando_json=json.load(f)
                
            guardando_json.append(mensagem)
            with open(f'{msg.topic}.json','w') as f:
                json.dump(guardando_json,f)









  




      

  
      
  
      
  
  

client = mqtt.Client("python3") 
client.on_connect = on_connect 
client.on_message = on_message 
  
client.connect(HOST, PORT, keepalive,bind_address) 
  
client.loop_start() 
while Connected != True: 
    time.sleep(1)#time to wait a start a connection 
  
try: 
    while True: 
        time.sleep(1) 
        client.subscribe(TOPIC) 
  
except KeyboardInterrupt: 
    print('\nSaindo') 
    client.disconnect() 
    client.loop_stop
